### PR TITLE
Ntd1hc/feat/enhance robotlog2db tool

### PR DESCRIPTION
**Pull request by ngoan1608**
Hi Holger,
Hi Thomas,

This changes in this PR are aligned with changes in [PyTestLog2DB repos](https://github.com/test-fullautomation/python-pytestlog2db/pull/20).

Please review the functionalities of the changes. I am updating document accordingly.

Thank you,
Ngoan

### CODE REVIEW

**Review by HolQue — CHANGES_REQUESTED** [review]
Line 
`
_tbl_case_component   = metadata_info['component']`

causes crash (key error 'component').

**Comment by ngoan1608** [comment]
> Line ` _tbl_case_component = metadata_info['component']`
> 
> causes crash (key error 'component').

Hi Holger,

This is my fault, I have pushed 2 last commits which fixed this issue into personal remote instead of this repo.
I have just pushed them to this repo. Please pull the latest changes and help me to double-check.

Thank you,
Ngoan

**Comment by HolQue** [comment]
Hi Ngoan,

works fine now!

**Comment by ngoan1608** [comment]
Hi Holger,

I have added new commits to implement a validation of xmlresultfile with robot result schema (_robot.xsd_ file) which you mentioned in issue #26.
The xml result file(s) will be validated at the first step so it will avoid such errors related to result when importing.

The schema _robot.xsd_ is updated with the new `UNKNOWN` state (implemented by us in robotframework core) so that the xml result which is generated by RobotRramework AIO should work properly.

Please help to double-check the changes.

Thank you,
Ngoan

**Comment by ngoan1608** [comment]
Issue #25 is also fixed with new commits.

**Comment by HolQue** [comment]
Hi Ngoan,

you need to extend the

`"PACKAGEDATA" : ["*.pdf"],`

by

`"PACKAGEDATA" : ["*.pdf","./xsd/*.xsd"],`

to get the xsd file installed also ;-)

**Comment by HolQue** [comment]
And unfortunately an XML syntax error still causes a crash:

lxml.etree.XMLSyntaxError: Opening and ending tag mismatch: testsuitesXYZ line 1 and testsuites, line 1, column 19500

You need to use try/except when opening an XML file.

**Review by test-fullautomation — APPROVED** [review]
Hi Ngoan,
very good!
Thomas

**Comment by test-fullautomation** [comment]
Hi Ngoan,

I overlooked the finding from Holger at the end.
Please create a new pull-request for this issue.

Thank you,
 Thomas

**Pull request merged**
