### PR TITLE
Ntd1hc/feat/maintain document with genpackagedoc

### PR DESCRIPTION
**Pull request by ngoan1608**
Hi @ThPoll ,
Hi @HolQue ,

Please support to review the document's changes to adapt with genpackagedoc.

Thank you,\
Ngoan

### CODE REVIEW

**Comment by HolQue** [comment]
The frameworks spelling should be aligned: either "Robot Framework" or "RobotFramework AIO"
Please refer to robotframework-documentation\book\StyleGuide.pdf, chapter 5.1 Abbreviations

**Comment by HolQue** [comment]
Typing mistake: 5.11 Function: normailze path

**Comment by HolQue** [comment]
Findings collected in a better format
[RobotResults2DB_review.pdf](https://github.com/test-fullautomation/robotframework-testresultwebapptool/files/9418210/RobotResults2DB_review.pdf)
:

**Comment by ngoan1608** [comment]
Hi @HolQue ,

I have just added new commit to update the document as per your comments.
Please help to double check the changes.

Regarding to your question at point (14), it is just an example for the definition, not required to hardcode. Our Robot Framework AIO will handle this definitions within `Suite Setup` of `RobotFramework_Testsuites` library (I added new hint below the sample testcase in document). 
In case user do not use `RobotFramework_Testsuites` library, they can define the robot keyword to get Robot Framework version instead of hardcoding the value.

Thank you,
Ngoan

**Review by test-fullautomation — APPROVED** [review]
Hi Ngoan,

looks very nice!

Thank you,
 Thomas

**Comment by HolQue** [comment]
Hi Ngoan,

I agree, very good documentation now!

**Pull request merged**
