### PR TITLE
update tool's document

### PR DESCRIPTION
**Pull request by ngoan1608**
Hi Holger,
Hi Thomas,

This PR contains updates in document for below tickets:
- https://github.com/test-fullautomation/robotframework-robotlog2db/issues/24
  + Introduction section: I have add the overview picture and tool's abilities, remove the detail information (Metadata, Tags, ...) and re-organize links in the sentences.
  + Description section:
     - I added more information why we need the Metadata and Tags setting in Robot Framework test case.
     - Hints have been removed or re-located properly. 
     - **Robot Framework test case** is used for proper name.
     - Typos are fixed.
     - Change the words to avoid confusion for users. But maybe there is some confused words there :).
     - Regarding to the suggestion for separated section for user who using **RobotFramework AIO**, I think it is not required (tool can work standalone and **TestsuitesManagement** just involves in the small part of Metadata settings ) so I keep it as a hint in the sample Robot Framework test case setting section. => Please give your idea about this point
- https://github.com/test-fullautomation/robotframework-robotlog2db/issues/29
  => More explanation about the usage of component mapping.

Please review and give your feeling about the updates.
Then, I will align it for the document of PyTestLog2DB.

Thank you,
Ngoan

### CODE REVIEW

**Review by HolQue — COMMENTED** [review]
Very good! And so much better than before. Really helpful now and good document structure. I like!

**Review by test-fullautomation — APPROVED** [review]
Hi Ngoan,
looks good to me!
Thank you,
  Thomas

**Review by test-fullautomation — CHANGES_REQUESTED** [review]
Hi Ngoan,
please solve the merge conflict.
Thank you,
 Thomas

**Comment by ngoan1608** [comment]
Hi Thomas,

The conflict has been solved and document has been updated to latest tool's version.

Thank you,
Ngoan

**Pull request merged**
